# # Dockerfile.dev (client)
# FROM node:20-alpine

# WORKDIR /client

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 3000
# CMD ["npm", "run", "dev"]

# Dockerfile.dev (client)
FROM node:20

WORKDIR /client

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]